version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: app
      MYSQL_DATABASE: crud_products_api
      MYSQL_USER: cpa
      MYSQL_PASSWORD: products
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local
